package graph

import (
	"slices"
	"testing"
)

func TestExtractMarksGeneratedFiles(t *testing.T) {
	tests := []struct {
		name   string
		rel    string
		source string
		want   bool
	}{
		{name: "go banner", rel: "models.go", source: "// Code generated by sqlc. DO NOT EDIT.\n// versions: sqlc v1.27.0\n\npackage db\n\nfunc Get() {}\n", want: true},
		{name: "go banner below a build tag", rel: "mock.go", source: "//go:build tools\n\n// Code generated by MockGen. DO NOT EDIT.\npackage db\n\nfunc Get() {}\n", want: true},
		{name: "generated tag", rel: "schema.ts", source: "/**\n * @generated SignedSource<<abc>>\n */\nexport function get() {}\n", want: true},
		{name: "protoc python", rel: "api_pb2.py", source: "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n# source: api.proto\n\ndef get():\n    pass\n", want: true},
		{name: "hand-written", rel: "store.go", source: "// Package db stores rows.\npackage db\n\nfunc Get() {}\n"},
		{name: "generated without do not edit", rel: "gen.go", source: "// Code generated from the schema, then edited by hand.\npackage db\n\nfunc Get() {}\n"},
		{name: "banner text in a string", rel: "lint.go", source: "package db\n\nconst banner = \"// Code generated by x. DO NOT EDIT.\"\n\nfunc Get() {}\n"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := extractFile(tt.rel, tt.source)
			if err != nil {
				t.Fatalf("extractFile(%q) error = %v, want nil", tt.rel, err)
			}
			if len(got.nodes) < 2 {
				t.Fatalf("extractFile(%q) nodes = %+v, want the file and its function", tt.rel, got.nodes)
			}
			for _, node := range got.nodes {
				if node.Generated != tt.want {
					t.Errorf("extractFile(%q) node %s Generated = %t, want %t", tt.rel, node.ID, node.Generated, tt.want)
				}
			}
		})
	}
}

func TestGeneratedCodeFollowsProductionCode(t *testing.T) {
	root, graph := buildAnalysisRepo(t, map[string]string{
		"app.go": "package app\n\nfunc used() {}\n\nfunc Run() { used(); lookup() }\n\nfunc orphan() {}\n\nfunc lookup() {}\n",
		"models.go": "// Code generated by sqlc. DO NOT EDIT.\n\npackage app\n\n" +
			"func generatedOrphan(x int) int {\n\tif x > 0 && x < 9 {\n\t\treturn 1\n\t}\n\treturn 0\n}\n\nfunc lookupRow() {}\n",
	})

	report, err := FindDeadCode(graph, root, "")
	if err != nil {
		t.Fatalf("FindDeadCode() error = %v, want nil", err)
	}
	if slices.ContainsFunc(report.Symbols, func(symbol DeadSymbol) bool { return symbol.Node.Name == "generatedOrphan" }) {
		t.Errorf("FindDeadCode() = %+v, want generated code left out", report.Symbols)
	}
	if !slices.ContainsFunc(report.Symbols, func(symbol DeadSymbol) bool { return symbol.Node.Name == "orphan" }) {
		t.Errorf("FindDeadCode() = %+v, want production orphan listed", report.Symbols)
	}

	ranked, err := MostComplex(graph, "")
	if err != nil {
		t.Fatalf("MostComplex() error = %v, want nil", err)
	}
	if slices.ContainsFunc(ranked, func(node NodeV1) bool { return node.Name == "generatedOrphan" }) {
		t.Errorf("MostComplex() = %+v, want generated code left out", ranked)
	}

	result, err := Ask(graph, "lookup", AskOptions{})
	if err != nil {
		t.Fatalf("Ask(lookup) error = %v, want nil", err)
	}
	production := slices.IndexFunc(result.Hits, func(hit AskHit) bool { return hit.Pointer == "app.go:L9-L9" })
	generated := slices.IndexFunc(result.Hits, func(hit AskHit) bool { return hit.Pointer == "models.go:L12-L12" })
	if production < 0 || generated < 0 || production > generated {
		t.Errorf("Ask(lookup).Hits = %+v, want app.go's lookup before models.go's lookupRow", result.Hits)
	}

	found, err := Grep(graph, root, "lookup", GrepOptions{})
	if err != nil {
		t.Fatalf("Grep(lookup) error = %v, want nil", err)
	}
	last := found.Groups[len(found.Groups)-1]
	if last.Path != "models.go" || !last.Generated || slices.ContainsFunc(found.Groups[:len(found.Groups)-1], func(group GrepGroup) bool { return group.Generated }) {
		t.Errorf("Grep(lookup).Groups = %+v, want only models.go marked generated, after production code", found.Groups)
	}
}
